from pydantic import BaseModel, Field

class DevOutput(BaseModel):
    """
    Represents the output of a single file development.
    """
    path: str = Field(
        description="The file path where the output is to be stored.",
    )
    code: str = Field(
        description="The code content generated by the development process.",
    )

class DevOutputList(BaseModel):
    """
    Represents a list of DevOuput objects
    """
    response: list[DevOutput] = Field(
        description="A list of DevOutput objects representing the output of multiple files.",
    )

